# -*- coding: utf-8 -*-
"""aula 02.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tTdDffzyVNOFDVREnQJPobfRlzxRKbpd
"""

#1 crie um sistema que some 2 numeros:

numero = "10"
numero2 = "55"
print(numero + numero2)


#2 crie um sistema que imprima seu nome na tela

# nome =  ("leandro")
# print (nome)

#3 crie um sistema que imprima seu nome e um cumprimento apos o nome:

# text = input ("digite um cumprimento")
# nome = input ("digite seu nome - ")
# print ("ola tudo bem?" , nome )

#4 crie um sistema para multiplicar dois numeros

# numero = 10
# numero2 = 55
# print(numero, * numero2)